services:
  - type: web
    name: qdrant-vector-db
    runtime: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    region: oregon
    plan: free  # ← CHANGED TO FREE
    
    healthCheckPath: /
    
    envVars:
      - key: QDRANT__SERVICE__HTTP_PORT
        value: 6333
      - key: QDRANT__SERVICE__GRPC_PORT
        value: 6334
      - key: QDRANT__LOG_LEVEL
        value: INFO
      - key: QDRANT__SERVICE__HOST
        value: 0.0.0.0
      # Storage will be in-memory for free tier
      - key: QDRANT__SERVICE__API_KEY
        generateValue: true
    
    # REMOVED disk section - not available on free tier
    
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .